volumes:
  postgres_data:

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: prefect
      POSTGRES_DB: prefect
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U prefect" ]
      interval: 10s
      timeout: 5s
      retries: 5

  prefect-server:
    build: .
    command: ["uv", "run", "prefect", "server", "start", "--host", "0.0.0.0"]
    ports:
      - "4200:4200"
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://prefect:prefect@postgres:5432/prefect
    depends_on:
      postgres:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
            - .git/
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./docker-compose.yml
        - action: rebuild
          path: ./Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200/dashboard"]
      interval: 3s
      timeout: 5s
      retries: 10

  prefect-worker:
    build: .
    command: >
      uv run prefect worker start --pool "worker"
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api
    depends_on:
      prefect-server: { condition: service_healthy }
    restart: on-failure
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./docker-compose.yml
        - action: rebuild
          path: ./Dockerfile
