[project]
name = "prefect-workflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "prefect[sqlalchemy]>=3.4.5",
    "prefect-github>=0.3.1",
]
